
#######################################################
## DB 설정


spring:
  datasource:
    url: jdbc:mysql://sungwookhwang.iptime.org:3306/metachurch?characterEncoding=UTF-8&serverTimezone=UTC
    username: metachurch
    password: apxkcjfcl1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  app.datasource:
    url: jdbc:mysql://sungwookhwang.iptime.org:3306/metachurch?characterEncoding=UTF-8&serverTimezone=UTC
    username: metachurch
    password: apxkcjfcl1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  module.datasource:
    url: jdbc:mysql://sungwookhwang.iptime.org:3306/metachurch?characterEncoding=UTF-8&serverTimezone=UTC
    username: metachurch
    password: apxkcjfcl1!
    driver-class-name: com.mysql.cj.jdbc.Driver

#######################################################

spring.http.encoding:
  charset: UTF-8
  enabled: true
  force: true

server:
  url: http://localhost:9090/
  port: 9090
  tomcat:
    max-http-form-post-size: 10000MB

spring.servlet.multipart:
  max-file-size: -1 # 무제한
  max-request-size: -1 # 무제한

spring.thymeleaf:
  cache: false # 페이지수정시 바로바로 적용이 되도록 하기 위함
  prefix: classpath:/templates/
  suffix: .html

cmmn-properties:
  rsc-ver: 1.805
  active: local
  jwt:
    token-validity-in-seconds: 1800
  ehcache-config : classpath:com/cgmoffice/core/ehcache/ehcache.xml # ehcache 설정파일경로
  pdfDir: /pdf_storage # pdf 파일을 저장한 폴더명
  makeDbBackup: # db 백업 파일 관련 설정
    # 테이블 리스트
    dbTableList: TB_AUTH,TB_CLUS_ADD_INF,TB_CLUS_ITM_SET_MST,TB_CM_FILE,TB_DTL_CD,TB_ETC_CLUS_INFO,TB_GRP_CD,TB_INDV_CLUS_CRTMXT_LST,TB_INDV_CLUS_CRT_MPPG_LST,TB_INDV_CLUS_MERGEADD_INF,TB_INDV_CLUS_MERGE_INF,TB_INDV_CLUS_PRDT_MST,TB_INDV_CLUS_RCV_DTL,TB_INDV_CLUS_RCV_MST,TB_LGN_LST,TB_MEM,TB_MENU,TB_MSG,TB_PRDT_CLUS_MST,TB_PRDT_ETC_CLUS_INFO,TB_PRDT_INFO_CHG_LST,TB_PRDT_INFO_MST,TB_SYS_ERRLOG_LST
    ext: .sql
    backupFileDir: /BOX/DATABASE_SQL/
  fileMng: # 파일업로드관련 설정
    uploadRootPath: C:/cmmn-dev/temp # 파일업로드 root 경로
    uploadDenyExtList: exe,jsp,php,aspx,bat,vbs,dll,jspx,asp,java,pdb,msi,cab,swf # 파일업로드 거부 확장자목록
    uploadVideoMaxSize: 20000000000 # 동영상파일 업로드 최대사이즈 (Byte)
    uploadAudioMaxSize: 100000000 # 오디오파일 업로드 최대사이즈 (Byte)
    uploadMaxSize: 20000000 # 파일업로드 최대사이즈 (Byte)
  httpCall: # http 호출관련 설정
    maxConnections: 50 # connection 최대 연결 수
    pendingAcquireTimeoutSeconds: 5 # connection 최대 연결 수 초과시 연결대기 시간
    connectTimoutMillis: 5000 # remote 연결 타임아웃
    responseTimeoutSeconds: 10 # remote 응답 타임아웃
    allowed-origins:
      - http://106.244.74.67:8082/
      - https://jinsolins.kr/
      - https://www.jinsolins.kr/
      - http://192.168.0.9:8088/
  schedule-setting:
    makeDbBackupFilesCron: "0 0 0 * * *" # 매일 자정 마다 실행
    cron01: "0 */30 * * * *" # 매시 정각과 30분(즉, 30분 단위로 실행)
    cron02: "*/5 * * * * *" # 5초단위
    cron03: "*/6 * * * * *" # 6초단위
  # 라이센스파일경로
  license.mgr.jar.path: /Users/sungwookhwang/TEMP/BBB/cmmn-clus-license-keymgr-1.0-guarded.jar
  aes256-key: D7l5D72pehwsTuQnl5dTuQnl5D72pe2pedTuQnlndTuQnlnl5DD72pedTuQnl5D72pedTuQnl5D72pedTuQnl5D72